// Original sprites: lit tops, middle-tone faces and dark sides preserve depth.
export const palette: Record<string, string> = {
  K: '#171320',
  D: '#393042',
  S: '#696074',
  C: '#f5efd9',
  L: '#bad65a',
  G: '#738b3c',
  B: '#425331',
  Y: '#efc24b',
  O: '#ad7b3d',
  A: '#b4d4c0',
  T: '#557a80',
  R: '#ee897e',
};
export const saucerPixels = [
  '...........CCCCCCC...........',
  '.........CCAAAAATTCC.........',
  '........CAACAAAATTTTC........',
  '........CACAAAATTTTTC........',
  '.......CAAAAAATTTTTTTC.......',
  '.......CAAAAKKKKTTTTTC.......',
  '.......CAAAAKALKTTTTTC.......',
  '.....CCCCCCCKKKKCCCCCCC......',
  '...CCLLLLLLLLLLLLLLLLLLLCC...',
  '.CCLLLLLLLLLLLLLLLLLLLLLLLCC.',
  'CLLLLCCLLLLCCLLLLCCLLLLCCLLLC',
  'CGGGGKKGGGGKKGGGGKKGGGGKKGGGC',
  '.CCGGGGGGGGGGGGGGGGGGGGGGGCC.',
  '...CCBBBBBBBBBBBBBBBBBBBCC...',
  '.....CCCCCCCCCCCCCCCCC......',
  '..........GLLLLLG...........',
  '...........CCCCC............',
];
export const junkPixels = [
  [
    '...CCCCCCCCCCCCCCCC...',
    '..CLLLLLLLLLLLLLLLLG..',
    '..CLLLCLLLLCLLLLCLLG..',
    '..CLLLLLLLLLLLLLLLLG..',
    '.YYYLLLLLLLLLLLLLLLYYY',
    'CYOOCCCCCCCCCCCCCCYOO',
    'CYOOCLLLLLLLLLLLLGYOO',
    'CYOOCLLLLLLLLLLLLGYOO',
    'CYOOCCCCCCCCCCCCCCYOO',
    '.OOOGGGGGGGGGGGGGGOO.',
    '.OOOBBBBBBBBBBBBBBOO.',
    '..OO..............OO.',
    '..KK..............KK.',
  ],
  [
    '....CCCCCCCCCCCC...',
    '...CCCCCCCCCCCCCC..',
    '..CCOCCCOCCCOCCCOS.',
    '.CCCCCCCCCCCCCCCOS.',
    'CCOCCCOCCCOCCCCCOS.',
    'CCCCCCCCCCCCCCCCOS.',
    'CCCOCCCOCCCOCCCCOS.',
    'CCCCCCCCCCCCCCCCOS.',
    'COCCCOCCCOCCCCCCOS.',
    'CCCCCCCCCCCCCCCCOS.',
    'OOOOOOOOOOOOOOOOOS.',
    'SSSSSSSSSSSSYCCSS..',
    'SSSSSSSSSSSSYCCS...',
  ],
  [
    '.........CCCCCC......',
    '.......CCYYYYYYOO....',
    '.....CCYYYYYYOOYYOO..',
    '...CCYYYYYYOOYYYYOO..',
    '.CCYYYYYYOOYYYYYYOO..',
    'CYYYYYYOOYYYYYYYYOO..',
    'CYYYYOOYYYYYYYYYYOO..',
    'COOOOYYYYYYYCCYYYOO..',
    'COYYOYYYYYYYCCYYYOO..',
    'COYYOYYYYYYYYYYYYOO..',
    'COYYOYYYYYYYYYYYYOO..',
    'COYYOYYYYYYYYYYYYOO..',
    '.OYYOYYYYYYYYYYYYOO..',
    '..OOOYYYYYYYYYYYYO...',
    '....OOOOOOOOOOOOO....',
  ],
  [
    '...CCCCCCCCCC...',
    '..CCCCCCCCCCCC..',
    '.CCCCCCCCCCCCTS.',
    '.CCCCCCCCCCCCTS.',
    '.CCKCCCCCCCCTTS.',
    '.CCKCCCCCCCCTTS.',
    '.CCCCCCCCCCCTTS.',
    '.SSSSSSSSSSSTTS.',
    '.CCCCCCCCCCCTTS.',
    '.CCCCCCCCCCCTTS.',
    '.CCKCCCCCCCCTTS.',
    '.CCKCCCCCCCCTTS.',
    '.CCKCCCCCCCCTTS.',
    '.CCCCCCCCCCCTTS.',
    '.CCCCCCCCCCCTTS.',
    '.CCCCCCCCCCCTTS.',
    '..SSSSSSSSSSSS..',
    '..KK.......KK...',
  ],
  [
    '.....SSSSSS.....',
    '...SSDKKDKKSS...',
    '..SDKKKKKKKKKS..',
    '.SDKKKCCCCKKKKS.',
    '.SKKKCCSSCCKKDS.',
    'SKDKCCDKKDCCKKS.',
    'SKKKCSDKKDSCKDS.',
    'SKDKCSDKKDSCKKS.',
    'SKKKCCDKKDCCKDS.',
    '.SDKKCCSSCCKKKS.',
    '.SKKKKCCCCKKKDS.',
    '..SSKKKKKKKKSS..',
    '...SSDKKDKKSS...',
    '.....SSSSSS.....',
  ],
  [
    '....C.........C.....',
    '.....C.......C......',
    '......C.....C.......',
    '..CCCCCCCCCCCCCC....',
    '.CYYYYYYYYYYYYYYOO..',
    'CYCCCCCCCCCCYYYYOO..',
    'CYCAAAAAATTTCYCYOO..',
    'CYCATTTTTTTTCYYYOO..',
    'CYCATTTTTTTTCYKYOO..',
    'CYCTTTTTTTTTCYYYOO..',
    'CYCTTTTTTTTTCYKYOO..',
    'CYCCCCCCCCCCYYYYOO..',
    '.OOOOOOOOOOOOOOOO...',
    '..OO..........OO....',
    '..KK..........KK....',
  ],
];
export const carPixels = [
  '........CCCCCCCC...........',
  '.......CRAAAAATTCC.........',
  '......CRAAAAATTTTTC........',
  '.C....CRAAAATTTTTTTC.......',
  '.RC...CRRRRRRRRRRRRCC......',
  '.RRCCCCRRRRRRRRRRRRRRCC....',
  '.RRRRRRRRRRRRRRRRRRRRRRC...',
  'CRRRRRRRRRRRRRRRRRRRRRRRY..',
  'CCCCCCCCCCCCCCCCCCCCCCCCCC.',
  '.OOOOOOOOOOOOOOOOOOOOOOOO..',
  '..KKCCKK........KKCCKK.....',
  '..KCSSCK........KCSSCK.....',
  '...KCCK..........KCCK......',
  '....KK............KK.......',
];
// The logo's rocket fin, piled junk, segmented bed and streamlined cab.
export const truckPixels = [
  '........LL............................................................',
  '........LCL...........................................................',
  '.........LCL..........................................................',
  '.........LCCL.............LLLL........................................',
  '..........LCCL.....LLL...LLCCCL...LLLL.................................',
  '..........LCCCL...LCCCL.LCCCLL...LCCCCL................................',
  '...........LCCCL.LCCCLL.LCCLLL..LCCCCCCL...............................',
  '...........LCCCLLLCLLCL..LLCCCL.LCCCCCCL......LLLLLL...................',
  '............LCCLLLLCCCL.LCCCCCL..LLLLLL....LLLAAAAAALLL................',
  '..........LLLLLCCCLCCLLLCCCCCLLLLCCCCL..LLLAAAAAAAAAAAALL..............',
  '........LLCCCCCLLLLCCLCCCCLLLLCCLCCCCLLLAAAAAAAAAAAAAAAALL.............',
  '.........LLLLLLLCCCLLLCCCCLCCCLLLCCCCLAAAAAAAALLLLLLLLLLLLL............',
  '..........LCCCCCLLLLLLLLLLLLCCCCLLLLLAAAAAALLTTTTTTTTTTTTTL............',
  '..........LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLTTTTTTTTTTTTTTLL...........',
  '..........LKKKKKKLKKKKKKKLKKKKKKKLKKKKKKLKLTTTTTTTTTTTTTTTL...........',
  '..........LKKKKKKLKKKKKKKLKKKKKKKLKKKKKKLKLTTTTTTTTTTTTTTTLL..........',
  '..........LKKKKKKLKKKKKKKLKKKKKKKLKKKKKKLKLLLLLLLLLLLLLLLLLLL..........',
  '..LL......LKKKKKKLKKKKKKKLKKKKKKKLKKKKKKLKLTTTTTTTTTTTTTTTTTL.........',
  '....LLLLLLLKKKKKKLKKKKKKKLKKKKKKKLKKKKKKLKLTTTTTTTTTTTTTTTTTLL........',
  '......LLLLLKKKKKKLKKKKKKKLKKKKKKKLKKKKKKLKLTTTTTTTTTTTTTTTTTTLL.......',
  '....LL....LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLKLLLLLLLLLLLLLLLLLLLLLL......',
  '......LLLLLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGLLLYLKKKKKKKKKKKKKKKKL.......',
  '..........LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLKKKKKKKKKKKKKKKKLL......',
  '..............LCCL....LCCL....LCCL....LCCL.....LLLLLLLLLLLLLLLLLL.....',
  '.............LKKKKL..LKKKKL..LKKKKL..LKKKKL...LLKKKKLLKKKKKKKKKKL....',
  '.............LKKKKL..LKKKKL..LKKKKL..LKKKKL..LKKKKKKLKKKKKKKKKKKL....',
  '..............LCCL....LCCL....LCCL....LCCL...LKKKKKKLLLLLLLLLLLLLL....',
  '............................................LLKKLL....................',
];
